name: What is this You work forty hours a week doing nothing
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Will
      uses: actions/checkout@v2
    - name: Testing this workflow
      run: echo Son of a .... He stole my line