name: Your not perfect sport
on: [push]

jobs:
  build:
   runs-on: macos-latest
   steps:
     - name: Robin
       uses: actions/checkout@v1
     - name: Son of a B Stole my line
       run: echo This is a beautiful feeling